version: "3"
services:
  ble:
    networks:
      - outside
    deploy:
      placement:
        constraints:
          - node.labels.bluetooth == true
      replicas: 1
      resources:
        limits:
          cpus: '0.40'
          memory: 128M
      restart_policy:
        condition: any
        delay: 5s
    image: chrisns/ble-eq3-awsiot:${DRONE_BUILD_NUMBER}
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_IOT_ENDPOINT_HOST=${AWS_IOT_ENDPOINT_HOST}
      - AWS_REGION=${AWS_REGION}

networks:
  outside:
    external:
      name: "host"